## This Plugin was written by Robert Kratz on 11. Mai 2021
## You need help with setting up the Plugin? Check out my Discord: https://link.rjks.us/support

## If you need a translated version of the Plugin -> https://link.rjks.us/buildffa-v1
## Wenn du eine übersetzte Version des Plugins brauchst -> https://link.rjks.us/buildffa-v1


enabled: false
database: false

## Database Structure

mysql:
  user: 'root'
  password: ''
  host: 'localhost'
  database: 'game'
  port: '3306'

## Here you can plug in your own coin system if you have one, just user the same database
## and define your uuid row and coins row and the plugin will use your coin System
## NOTICE: ONCE DEFINED, WE DO NOT RECOMMEND CHANGING THESE VALUES!

coins:
  table: 'game_coins'
  uuid-row: 'uuid'
  coins-row: 'coins'

stats:
  table: 'buildffa_stats'
  uuid-row: 'uuid'
  kills-row: 'kills'
  deaths-row: 'deaths'

shop:
  table: 'buildffa_shop'
  uuid-row: 'uuid'
  item-row: 'item'

sort:
  table: 'buildffa_sort'
  uuid-row: 'uuid'
  data-row: 'data'

selected:
  table: 'buildffa_perks_selected'
  uuid-row: 'uuid'
  category-row: 'category'
  data-row: 'data'

## Rank System Config

enable-rank-system: false
enable-tab-rank: false
enable-chat-rank: false
display-effect-on-player: false
enable-color-armor-by-rank: false
display-effect-on-top-while-sneaking: false

## Ingame Config

enable-player-joins-message: true
enable-player-leaves-message: true

allow-damage: true
allow-item-move-in-inventory: true
auto-unbreakable: true

block-disapear-after: 5
game-action-bar-enabled: true
show-score-board: true
hearts-when-join: 20.0

## Kill Event, to use stats and coins mysql must be enabled on the server
enable-coins-system: true
enable-stats-system: true

killer-coins-on-kill: 5
player-lose-coins-on-death: 2

killstreak-bonus-coins: 5

kill-streak-bonus-coins:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20

kill-streak-broadcast:
  - 3
  - 5
  - 10
  - 15
  - 20
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - 100
  - 150
  - 200
  - 500
  - 1000

## This requires a minimum of 2 maps in the cache
map-change-counter-enabled: true
map-change-counter: 500
map-change-counter-allow-two-maps-in-a-row: false

map-change-announcement-in-chat:
  - 500
  - 250
  - 100
  - 50
  - 30
  - 10
  - 5
  - 3
  - 2
  - 1

## If a Player executes the command /skip, the countdown will be set to the set number below
map-skip-countdown-to: 5
map-skip-countdown-possible-only-at-second: 100

permissions:
  operator: system.game.operator
  skip: system.game.cmd.skip
  always-skip: system.game.cmd.skip.always
  forcemap: system.game.cmd.forcemap

## Inventory Sort

enable-item-sort: true
inventory-sort-slot: 3
inventory-sort-inventory-name: "&6&lInventory Sort"
item-inventory-sort:
  ==: org.bukkit.inventory.ItemStack
  type: FEATHER
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&6&lItem selection'

## Perks

enable-perks-sort: true
perks-slot: 5
item-perks:
  ==: org.bukkit.inventory.ItemStack
  type: CHEST
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&6&lPerks'

## Here you can configure the loot for a legendary chest, if you want to lower the chance of an item, just add more of other items to the list

luck-block-items:
  - ==: org.bukkit.inventory.ItemStack
    type: STONE_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&7Stone Sword'